"""PulsePrice full schema implementation

Revision ID: 144d5da1e3b8
Revises: 0466c18ca493
Create Date: 2026-05-02 21:29:59.795338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '144d5da1e3b8'
down_revision: Union[str, None] = '0466c18ca493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('old_price', sa.Numeric(), nullable=True),
    sa.Column('new_price', sa.Numeric(), nullable=True),
    sa.Column('drop_percent', sa.Numeric(), nullable=True),
    sa.Column('alert_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_meta_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('average_shipping_days', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_scraping_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('price_drop_alerts', sa.Boolean(), nullable=False),
    sa.Column('market_trend_reports', sa.Boolean(), nullable=False),
    sa.Column('price_rise_warnings', sa.Boolean(), nullable=False),
    sa.Column('new_deals', sa.Boolean(), nullable=False),
    sa.Column('websocket_live', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('display_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('compact_density', sa.Boolean(), nullable=False),
    sa.Column('animations_enabled', sa.Boolean(), nullable=False),
    sa.Column('show_ticker', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('WEBSOCKET', 'EMAIL', 'PUSH', name='deliverychannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('emoji_icon', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('my_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_when_added', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cached_lowest_comp_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cached_market_visibility_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_price_floor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price_ceiling', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_rank', sa.Integer(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='sellerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cached_market_visibility_pct >= 0 AND cached_market_visibility_pct <= 100', name='check_visibility_pct_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_competitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('aggressiveness', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='aggressiveness'), nullable=False),
    sa.Column('aggressiveness_description', sa.Text(), nullable=True),
    sa.Column('competitiveness', sa.Integer(), nullable=False),
    sa.Column('competitiveness_trend', sa.Integer(), nullable=False),
    sa.Column('spark_color', sa.String(length=10), nullable=False),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('competitiveness >= 0 AND competitiveness <= 1000', name='check_competitiveness_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('emoji_icon', sa.String(length=10), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('alert_condition', sa.Enum('BELOW_TARGET', 'ANY_CHANGE', 'DROP_10PCT', 'DROP_20PCT', name='alertcondition'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('seller_product_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_mode', sa.Enum('MARGIN_DROPS_BELOW', 'PRICE_UNDERCUT_BY', name='pricealerttrigger'), nullable=False),
    sa.Column('target_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('threshold_type', sa.Enum('ABSOLUTE', 'PERCENT', name='thresholdtype'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('risk_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'HEALTHY', name='risklevel'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_product_id'], ['seller_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_product_price_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_product_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_product_id'], ['seller_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopper_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('watchlist_item_id', sa.Uuid(), nullable=False),
    sa.Column('condition_type', sa.Enum('BELOW_TARGET', 'ANY_CHANGE', 'DROP_10PCT', 'DROP_20PCT', name='alertcondition'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_push', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress_pct >= 0 AND progress_pct <= 100', name='check_progress_pct_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_competitor_products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tracked_competitor_id', sa.Uuid(), nullable=False),
    sa.Column('seller_product_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('their_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_gap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('risk_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'HEALTHY', name='risklevel'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_product_id'], ['seller_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_competitor_id'], ['tracked_competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('email_verification_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('login_attempts', 'failure_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('user_sessions', sa.Column('device_info', sa.Text(), nullable=True))
    op.add_column('user_sessions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('user_sessions', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.add_column('user_sessions', sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('initials', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('google_sub', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'users', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'google_sub')
    op.drop_column('users', 'initials')
    op.drop_column('user_sessions', 'last_used_at')
    op.drop_column('user_sessions', 'is_revoked')
    op.drop_column('user_sessions', 'ip_address')
    op.drop_column('user_sessions', 'device_info')
    op.alter_column('password_reset_tokens', 'token_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('login_attempts', 'failure_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('email_verification_tokens', 'token_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_table('tracked_competitor_products')
    op.drop_table('shopper_alerts')
    op.drop_table('seller_product_price_history')
    op.drop_table('price_alerts')
    op.drop_table('watchlist_items')
    op.drop_table('tracked_competitors')
    op.drop_table('seller_products')
    op.drop_table('notification_deliveries')
    op.drop_table('display_preferences')
    op.drop_table('alert_preferences')
    op.drop_table('activity_logs')
    op.drop_table('platform_meta_registry')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
